services:
  mysql:
    image: mysql:latest
    container_name: ipath_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1cePath
      - MYSQL_DATABASE=ipath_old
    volumes:
      - mysql-data:/var/lib/mysql
      - C:/Daten/ipath_podman/backup:/opt/backup 

volumes:
  mysql-data:
